### ISSUE TITLE
Ryan Siegel

### ISSUE THREAD

**Issue by rwsiegel1223** [umiami-web-design/github-setup#42]
https://rwsiegel1223.github.io

**Comment by ebrown15** [comment]
No website?  Grade is posted in CaneLink.

**Comment by rwsiegel1223** [comment]
Dear Professor Brown,

Hope you had a great weekend!

Im not sure why the site is not opening in Github, I followed the
directions on the class website exactly, so maybe a small mistake was made
that ruined the entire link. I know it is a closed assignment without any
extensions to fix it, so I will discuss with you tomorrow in class to see
if there is anything I can do. If there is nothing that can be done then I
will make sure my work for the rest of the semester is done perfectly.

all the best,
Ryan Siegel
